blank_issues_enabled: false
contact_links:
  - name: Feature Requests & Questions
    url: https://github.com/KevinVandy/material-react-table/discussions
    about: Please ask and answer questions here, but don't report bugs here! That's what bug reports/issues are for!
  - name: Community Chat
    url: https://discord.gg/5wqyRx6fnm
    about: Join the Discord to discuss bugs, feature clarifications, and the general direction of the project!
